name: dddart_repository_mongodb_example
description: Examples for dddart_repository_mongodb package
version: 0.9.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  dddart:
    path: ../../dddart
  dddart_serialization:
    path: ../../dddart_serialization
  dddart_json:
    path: ../../dddart_json
  dddart_config:
    path: ../../dddart_config
  dddart_repository_mongodb:
    path: ../
  mongo_dart: ^0.10.0

dev_dependencies:
  build_runner: ^2.4.0
  lints: ^3.0.0

dependency_overrides:
  dddart:
    path: ../../dddart
  dddart_serialization:
    path: ../../dddart_serialization
  dddart_json:
    path: ../../dddart_json
