name: _dddart_workspace
publish_to: none

environment:
  sdk: '>=3.5.0 <4.0.0'

workspace:
  - packages/dddart
  - packages/dddart_serialization
  - packages/dddart_json
  - packages/dddart_rest
  - packages/dddart_rest_client
  - packages/dddart_config
  - packages/dddart_repository_mongodb
  - packages/dddart_repository_dynamodb
  - packages/dddart_repository_sql
  - packages/dddart_repository_sqlite
  - packages/dddart_repository_sqlite/example
  - packages/dddart_repository_mysql
  - packages/dddart_repository_mysql/example
  - packages/dddart_webhooks
  - packages/dddart_webhooks_slack
