name: _dddart_workspace
publish_to: none

environment:
  sdk: '>=3.5.0 <4.0.0'

workspace:
  - packages/dddart
  - packages/dddart_serialization
  - packages/dddart_json
  - packages/dddart_rest
  - packages/dddart_config
  - packages/dddart_repository_mongodb
  - packages/dddart_webhooks
  - packages/dddart_webhooks_slack
