name: dddart_repository_mysql_example
description: Examples for dddart_repository_mysql package
version: 0.9.0
publish_to: none

environment:
  sdk: ^3.5.0

resolution: workspace

dependencies:
  dddart:
  dddart_repository_mysql:
  dddart_repository_sql:
  dddart_serialization:

dev_dependencies:
  build_runner: ^2.4.0
  dddart_json:
