name: dddart_events_distributed_example
description: Examples for dddart_events_distributed package
publish_to: none

environment:
  sdk: '>=3.5.0 <4.0.0'

resolution: workspace

dependencies:
  dddart:
  dddart_events_distributed:
    path: ../
  dddart_serialization:
  shelf: ^1.4.0
  shelf_router: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.0
  test: ^1.24.0
