name: dddart
description: A lightweight Domain-Driven Design (DDD) framework for Dart that provides base classes and utilities to help developers implement DDD principles in their applications.
version: 0.9.0
homepage: https://github.com/continuousimagination/dddart
repository: https://github.com/continuousimagination/dddart
issue_tracker: https://github.com/continuousimagination/dddart/issues

resolution: workspace

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  uuid: ^4.0.0
  logging: ^1.2.0

dev_dependencies:
  test: ^1.24.0
  very_good_analysis: ^6.0.0