name: dddart_webhooks_slack_example
description: Example applications demonstrating dddart_webhooks_slack
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  dddart_webhooks:
    path: ../../dddart_webhooks
  dddart_webhooks_slack:
    path: ../
  shelf: ^1.4.0
  shelf_router: ^1.1.0

dependency_overrides:
  dddart:
    path: ../../dddart
  dddart_webhooks:
    path: ../../dddart_webhooks
  dddart_webhooks_slack:
    path: ../

dev_dependencies:
  lints: ^3.0.0
