name: dddart_http
description: HTTP CRUD API framework for DDDart - Provides RESTful endpoints for aggregate roots
version: 0.9.0
homepage: https://github.com/continuousimagination/dddart_http
repository: https://github.com/continuousimagination/dddart_http
issue_tracker: https://github.com/continuousimagination/dddart_http/issues

resolution: workspace

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  logging: ^1.2.0
  dddart: ^0.9.0
  dddart_serialization: ^0.9.0

dev_dependencies:
  test: ^1.24.0
  lints: ^3.0.0
