name: dddart_http
description: HTTP CRUD API framework for DDDart - Provides RESTful endpoints for aggregate roots
version: 0.9.0
homepage: https://github.com/continuousimagination/dddart
repository: https://github.com/continuousimagination/dddart
issue_tracker: https://github.com/continuousimagination/dddart/issues

resolution: workspace

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  dddart: ^0.9.0
  dddart_serialization: ^0.9.0
  dddart_webhooks:
    path: ../dddart_webhooks
  logging: ^1.2.0
  shelf: ^1.4.0
  shelf_router: ^1.1.0

dev_dependencies:
  test: ^1.24.0
  very_good_analysis: ^6.0.0
