name: dddart_http
description: HTTP CRUD API framework for DDDart - Provides RESTful endpoints for aggregate roots
version: 0.9.0
homepage: https://github.com/continuousimagination/dddart_http
repository: https://github.com/continuousimagination/dddart_http
issue_tracker: https://github.com/continuousimagination/dddart_http/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  dddart:
    path: ../dddart
  dddart_serialization:
    path: ../dddart_serialization

dev_dependencies:
  test: ^1.24.0
  lints: ^3.0.0
