name: dddart_json
description: JSON serialization support for DDDart - Domain-Driven Design for Dart
version: 0.9.0
homepage: https://github.com/continuousimagination/dddart_json
repository: https://github.com/continuousimagination/dddart_json
issue_tracker: https://github.com/continuousimagination/dddart_json/issues

resolution: workspace

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  dddart: ^0.9.0
  dddart_serialization: ^0.9.0
  build: ^2.4.0
  source_gen: ^1.4.0
  analyzer: ^6.0.0

dev_dependencies:
  test: ^1.24.0
  build_runner: ^2.4.0
  lints: ^3.0.0