name: dddart_repository_dynamodb_example
description: Examples for dddart_repository_dynamodb package
version: 0.1.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  aws_dynamodb_api: ^2.0.0
  dddart: any
  dddart_json: any
  dddart_repository_dynamodb: any
  dddart_serialization: any

dependency_overrides:
  dddart:
    path: ../../dddart
  dddart_json:
    path: ../../dddart_json
  dddart_repository_dynamodb:
    path: ../
  dddart_serialization:
    path: ../../dddart_serialization

dev_dependencies:
  build_runner: ^2.4.0
  very_good_analysis: ^6.0.0
