name: dddart_rest_example
description: Example application demonstrating dddart_rest RESTful CRUD API
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  dddart:
    path: ../../dddart
  dddart_serialization:
    path: ../../dddart_serialization
  dddart_rest:
    path: ../
  shelf: ^1.4.0

dependency_overrides:
  dddart:
    path: ../../dddart
  dddart_serialization:
    path: ../../dddart_serialization
  dddart_rest:
    path: ../

dev_dependencies:
  lints: ^3.0.0
