name: dddart_repository_sqlite_example
description: Examples for dddart_repository_sqlite package
version: 0.1.0
publish_to: none
resolution: workspace

environment:
  sdk: ^3.5.0

dependencies:
  dddart:
    resolution: workspace
  dddart_serialization:
    resolution: workspace
  dddart_json:
    resolution: workspace
  dddart_repository_sql:
    resolution: workspace
  dddart_repository_sqlite:
    resolution: workspace

dev_dependencies:
  build_runner: ^2.4.0
