name: dddart_serialization
description: Serialization framework for DDDart - Domain-Driven Design for Dart
version: 0.9.0
homepage: https://github.com/continuousimagination/dddart_serialization
repository: https://github.com/continuousimagination/dddart_serialization
issue_tracker: https://github.com/continuousimagination/dddart_serialization/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  dddart: ^0.9.0

dev_dependencies:
  test: ^1.24.0
  lints: ^3.0.0