name: dddart_serialization
description: Serialization framework for DDDart - Domain-Driven Design for Dart
version: 0.9.0
homepage: https://github.com/continuousimagination/dddart
repository: https://github.com/continuousimagination/dddart
issue_tracker: https://github.com/continuousimagination/dddart/issues

resolution: workspace

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  dddart: ^0.9.0

dev_dependencies:
  test: ^1.24.0
  very_good_analysis: ^6.0.0