name: dddart_http_example
description: Example application demonstrating dddart_http CRUD API
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  dddart:
    git:
      url: https://github.com/continuousimagination/dddart.git
  dddart_serialization:
    git:
      url: https://github.com/continuousimagination/dddart_serialization.git
  dddart_http:
    git:
      url: https://github.com/continuousimagination/dddart_http.git
  shelf: ^1.4.0

dev_dependencies:
  lints: ^3.0.0
