name: dddart_events_example
description: Example demonstrating DDDart domain events features
version: 0.9.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  dddart:
    git:
      url: https://github.com/continuousimagination/dddart.git

dev_dependencies:
  lints: ^3.0.0
