name: dddart_json_example
description: Example demonstrating DDDart JSON serialization features
version: 0.9.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  dddart:
    path: ../../dddart
  dddart_serialization:
    path: ../../dddart_serialization
  dddart_json:
    path: ../

dev_dependencies:
  build_runner: ^2.4.0
  test: ^1.24.0
