name: dddart_json_example
description: Example demonstrating DDDart JSON serialization features
version: 0.9.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  dddart:
    git:
      url: https://github.com/continuousimagination/dddart.git
  dddart_serialization:
    git:
      url: https://github.com/continuousimagination/dddart_serialization.git
  dddart_json:
    git:
      url: https://github.com/continuousimagination/dddart_json.git

dev_dependencies:
  build_runner: ^2.4.0
  test: ^1.24.0
