name: dddart_repository_sqlite
description: SQLite repository implementation for DDDart aggregate roots with code generation support
version: 0.9.0
homepage: https://github.com/continuousimagination/dddart
repository: https://github.com/continuousimagination/dddart
issue_tracker: https://github.com/continuousimagination/dddart/issues

resolution: workspace

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  analyzer: ^6.0.0
  build: ^2.4.0
  dddart:
    resolution: workspace
  dddart_json:
    resolution: workspace
  dddart_repository_sql:
    resolution: workspace
  dddart_serialization:
    resolution: workspace
  source_gen: ^1.4.0
  sqlite3: ^2.4.0

dev_dependencies:
  build_runner: ^2.4.0
  build_test: ^2.2.0
  test: ^1.24.0
  very_good_analysis: ^6.0.0
